# MIT License

# Copyright (c) 2022 Bosch Rexroth AG

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: 'ctrlX Build App'
description: 'Building ctrlX App'
author: 'Bosch Rexroth AG'

inputs:
  path-amd64-snap:
    description: 'Absolute path to the amd64 snap'
    required: false
    default: '*amd64.snap'
  path-arm64-snap:
    description: 'Absolute path to the amd64 snap'
    required: false
    default: '*arm64.snap'
  path-app-files:
    description: 'Path to the app files'
    required: false
    default: $GITHUB_WORKSPACE
  app-name:
    description: 'Name of App'
    required: false
    default: ${{ github.event.repository.name }}

outputs:
  path-app:
    description: 'Absolute path to the built app'
    value: ${{ steps.build-app.outputs.path-app }}

runs:
  using: "composite"
  steps:

    - run: "echo ::error::wrong OS, please select runs-on: ubuntu-latest && exit 1"
      if: runner.os != 'linux'
      shell: bash

    - id: build-app
      run: |
        cd ${{ inputs.path-app-files }}
        sudo mkdir -p public/snaps/amd64/release/
        sudo mkdir -p public/snaps/arm64/release/
        sudo cp ${{ inputs.path-amd64-snap }} public/snaps/amd64/release/
        sudo cp ${{ inputs.path-arm64-snap }} public/snaps/arm64/release/
        tar -cf ${{ inputs.app-name }}.app public
        #Output absolute path of the app file
        echo "path-app=$(realpath $(find -name '${{ inputs.app-name }}.app'))" >> $GITHUB_OUTPUT
      shell: bash