name: Update Major Tag

on:
  push:
    tags:
      - v**

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Update major version by each new tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}
          git config --global user.name "GitHub Actions"
          echo "Updating ${MAJOR} tag"
          git tag -fa ${MAJOR} -m "Update major version tag"
          git push origin ${MAJOR} --force